version: '3.3'

services:

  # This service name is just used within this stack, so no need trying to make it unique
  memory_db:

    # Container name should be unique if possible
    container_name: lucia_api_memory_db
    image: redis:6.0.9
    # 6379

  textract:
    container_name: lucia_api_textract
    build:
      context: ../aws-textract-reader/
      dockerfile: Dockerfile
    image: textract:latest
    ports:
      - "8000:8000"
    volumes:
      - ../aws-textract-reader/:/var/www/html
      - ../aws-textract-reader/.aws:/root/.aws

  web_app:
    container_name: lucia_api_app

    environment:
      - NODE_ENV=production
      - USE_SSL=false

    build:
        context: ../../
        dockerfile: .Dockerfile
        args:
            NODE_ENV: production

    depends_on:
      - textract
      - memory_db

    # you can use image directly here if you are not building a Dockerfile
    # Only should be unique if you wish to build it as an image, name here should be unique
    image: lucia_api_app:latest

    # Mounting is not required in live
    volumes:
      - /home/docker-apps/lucia-api/environs:/home/environs
      - /home/docker-apps/lucia-api/logs:/var/www/html/storage/logs
      - /home/docker-apps/lucia-api/app-data:/var/www/html/storage/app


    ports:
    - "${LAUNCH_HTTP_PORT}:80"
    - "${LAUNCH_HTTPS_PORT}:443"




